"""
Logical Names for Sheets and Columns
=====================================

These are the **code-facing** names used throughout the application.
They map to physical names/IDs via the workspace manifest.

Why Logical Names?
------------------
- Physical names in Smartsheet can change (user renames)
- Physical IDs are numbers (not readable in code)
- Logical names are stable, readable constants

Mapping Flow
------------
Code → Logical Name → Manifest → Physical ID → Smartsheet API

Example
-------
>>> from shared.logical_names import Sheet, Column
>>> from shared.manifest import get_manifest
>>> 
>>> manifest = get_manifest()
>>> sheet_id = manifest.get_sheet_id(Sheet.TAG_REGISTRY)
>>> column_id = manifest.get_column_id(Sheet.TAG_REGISTRY, Column.TAG_REGISTRY.FILE_HASH)

Naming Convention
-----------------
- Sheet names: UPPER_SNAKE_CASE (e.g., TAG_REGISTRY, LPO_MASTER)
- Column names: UPPER_SNAKE_CASE (e.g., FILE_HASH, SAP_REFERENCE)
- Folder names: UPPER_SNAKE_CASE with number prefix for ordering
"""


class Sheet:
    """Logical sheet names used in code."""
    
    # Root level
    REFERENCE_DATA = "REFERENCE_DATA"
    CONFIG = "CONFIG"
    MACHINE_MASTER = "00B_MACHINE_MASTER"
    
    # 01. Commercial and Demand
    LPO_MASTER = "LPO_MASTER"
    LPO_AUDIT = "LPO_AUDIT"
    LPO_INGESTION_STAGING = "01H_LPO_INGESTION"  # Staging sheet
    
    # 02. Tag Sheet Registry
    TAG_REGISTRY = "TAG_REGISTRY"
    TAG_SHEET_STAGING = "02H_TAG_SHEET_STAGING"  # Staging sheet
    
    # 03. Production Planning
    PRODUCTION_PLANNING = "PRODUCTION_PLANNING"
    PRODUCTION_PLANNING_STAGING = "03H_PRODUCTION_PLANNING_STAGING"  # Staging sheet
    NESTING_LOG = "NESTING_LOG"
    ALLOCATION_LOG = "ALLOCATION_LOG"
    
    # 04. Production and Delivery
    CONSUMPTION_LOG = "CONSUMPTION_LOG"
    REMNANT_LOG = "REMNANT_LOG"
    FILLER_LOG = "FILLER_LOG"
    DELIVERY_LOG = "DELIVERY_LOG"
    INVOICE_LOG = "INVOICE_LOG"
    INVENTORY_TXN_LOG = "INVENTORY_TXN_LOG"
    INVENTORY_SNAPSHOT = "INVENTORY_SNAPSHOT"
    SAP_INVENTORY_SNAPSHOT = "SAP_INVENTORY_SNAPSHOT"
    PHYSICAL_INVENTORY_SNAPSHOT = "PHYSICAL_INVENTORY_SNAPSHOT"
    OVERRIDE_LOG = "OVERRIDE_LOG"
    USER_ACTION_LOG = "USER_ACTION_LOG"
    EXCEPTION_LOG = "EXCEPTION_LOG"
    
    # 05. Material Mapping
    MATERIAL_MASTER = "MATERIAL_MASTER"
    MAPPING_OVERRIDE = "MAPPING_OVERRIDE"
    LPO_MATERIAL_BRAND_MAP = "LPO_MATERIAL_BRAND_MAP"
    MAPPING_HISTORY = "MAPPING_HISTORY"
    MAPPING_EXCEPTION = "MAPPING_EXCEPTION"
    PARSED_BOM = "PARSED_BOM"


class Folder:
    """Logical folder names."""
    
    COMMERCIAL_AND_DEMAND = "01_COMMERCIAL_AND_DEMAND"
    TAG_SHEET_REGISTRY = "02_TAG_SHEET_REGISTRY"
    PRODUCTION_PLANNING = "03_PRODUCTION_PLANNING"
    PRODUCTION_AND_DELIVERY = "04_PRODUCTION_AND_DELIVERY"
    MATERIAL_MAPPING = "05_MATERIAL_MAPPING"


class Column:
    """
    Logical column names organized by sheet.
    
    Usage:
        >>> Column.TAG_REGISTRY.FILE_HASH
        'FILE_HASH'
    """
    
    class COMMON:
        """Columns used across multiple sheets."""
        STATUS = "STATUS"
        CREATED_AT = "CREATED_AT"
        REMARKS = "REMARKS"
        CLIENT_REQUEST_ID = "CLIENT_REQUEST_ID"
    
    class CONFIG:
        """00a Config sheet columns."""
        CONFIG_KEY = "CONFIG_KEY"
        CONFIG_VALUE = "CONFIG_VALUE"
        EFFECTIVE_FROM = "EFFECTIVE_FROM"
        CHANGED_BY = "CHANGED_BY"
    
    class MACHINE_MASTER:
        """00b Machine Master columns."""
        MACHINE_ID = "MACHINE_ID"
        NAME = "NAME"
        VACUUM_BED_DIMENSIONS = "VACUUM_BED_DIMENSIONS"
        SQM_PER_HOUR = "SQM_PER_HOUR"
        AVAILABLE_SHIFTS = "AVAILABLE_SHIFTS"
        STATUS = "STATUS"
    
    class LPO_MASTER:
        """01 LPO Master LOG columns."""
        LPO_ID = "LPO_ID"
        CUSTOMER_LPO_REF = "CUSTOMER_LPO_REF"
        SAP_REFERENCE = "SAP_REFERENCE"
        CUSTOMER_NAME = "CUSTOMER_NAME"
        PROJECT_NAME = "PROJECT_NAME"
        LPO_STATUS = "LPO_STATUS"
        BRAND = "BRAND"
        WASTAGE_CONSIDERED_IN_COSTING = "WASTAGE_CONSIDERED_IN_COSTING"
        PRICE_PER_SQM = "PRICE_PER_SQM"
        PO_QUANTITY_SQM = "PO_QUANTITY_SQM"
        PO_VALUE = "PO_VALUE"
        TERMS_OF_PAYMENT = "TERMS_OF_PAYMENT"
        HOLD_REASON = "HOLD_REASON"
        TOTAL_ALLOCATED_COST = "TOTAL_ALLOCATED_COST"
        DELIVERED_QUANTITY_SQM = "DELIVERED_QUANTITY_SQM"
        DELIVERED_VALUE = "DELIVERED_VALUE"
        # New columns from manifest (v1.2.0)
        ALLOCATED_QUANTITY = "ALLOCATED_QUANTITY"
        PLANNED_QUANTITY = "PLANNED_QUANTITY"
        PO_BALANCE_QUANTITY = "PO_BALANCE_QUANTITY"
        BALANCE_VALUE_AED = "BALANCE_VALUE_AED"
        CURRENT_STATUS = "CURRENT_STATUS"
        REMARKS = "REMARKS"
        DELIVERED_DATE = "DELIVERED_DATE"
        APPROVAL_STATUS = "APPROVAL_STATUS"
        NUMBER_OF_DELIVERIES = "NUMBER_OF_DELIVERIES"
        SOURCE_FILE_HASH = "SOURCE_FILE_HASH"
        CLIENT_REQUEST_ID = "CLIENT_REQUEST_ID"
        FOLDER_URL = "FOLDER_URL"
        CREATED_BY = "CREATED_BY"
        UPDATED_AT = "UPDATED_AT"
        UPDATED_BY = "UPDATED_BY"
    
    class LPO_INGESTION_STAGING:
        """01h LPO Ingestion staging sheet columns."""
        CUSTOMER_LPO_REF = "CUSTOMER_LPO_REF"
        SAP_REFERENCE = "SAP_REFERENCE"
        CUSTOMER_NAME = "CUSTOMER_NAME"
        PROJECT_NAME = "PROJECT_NAME"
        BRAND = "BRAND"
        WASTAGE_CONSIDERED_IN_COSTING = "WASTAGE_CONSIDERED_IN_COSTING"
        PRICE_PER_SQM = "PRICE_PER_SQM"
        PO_QUANTITY_SQM = "PO_QUANTITY_SQM"
        PO_VALUE = "PO_VALUE"
        TERMS_OF_PAYMENT = "TERMS_OF_PAYMENT"
        REMARKS = "REMARKS"
        DELIVERED_DATE = "DELIVERED_DATE"
        CREATED_BY = "CREATED_BY"
        # Staging-specific fields
        API_STATUS = "API_STATUS"
        API_MESSAGE = "API_MESSAGE"
        PROCESSED_AT = "PROCESSED_AT"

    class TAG_REGISTRY:
        """02 Tag Sheet Registry columns."""
        TAG_ID = "TAG_ID"
        TAG_NAME = "TAG_NAME"
        DATE_TAG_SHEET_RECEIVED = "DATE_TAG_SHEET_RECEIVED"
        REQUIRED_DELIVERY_DATE = "REQUIRED_DELIVERY_DATE"
        LPO_SAP_REFERENCE = "LPO_SAP_REFERENCE"
        LPO_STATUS = "LPO_STATUS"
        LPO_ALLOWABLE_WASTAGE = "LPO_ALLOWABLE_WASTAGE"
        PRODUCTION_GATE = "PRODUCTION_GATE"
        BRAND = "BRAND"
        CUSTOMER_NAME = "CUSTOMER_NAME"
        PROJECT = "PROJECT"
        LOCATION = "LOCATION"
        ESTIMATED_QUANTITY = "ESTIMATED_QUANTITY"
        SHEETS_USED = "SHEETS_USED"
        WASTAGE_NESTED = "WASTAGE_NESTED"
        STATUS = "STATUS"
        PLANNED_CUT_DATE = "PLANNED_CUT_DATE"
        ALLOCATION_BATCH_ID = "ALLOCATION_BATCH_ID"
        SUBMITTED_BY = "SUBMITTED_BY"
        RECEIVED_THROUGH = "RECEIVED_THROUGH"
        REMARKS = "REMARKS"
        FILE_HASH = "FILE_HASH"
        CLIENT_REQUEST_ID = "CLIENT_REQUEST_ID"
    
    class TAG_SHEET_STAGING:
        """02h Tag Sheet Staging columns."""
        TAG_ID = "TAG_ID"
        DATE_TAG_SHEET_RECEIVED = "DATE_TAG_SHEET_RECEIVED"
        TAG_SHEET_NAME_REV = "TAG_SHEET_NAME_REV"
        REQUIRED_DELIVERY_DATE = "REQUIRED_DELIVERY_DATE"
        LPO_SAP_REFERENCE_LINK = "LPO_SAP_REFERENCE_LINK"
        LPO_STATUS = "LPO_STATUS"
        LPO_ALLOWABLE_WASTAGE = "LPO_ALLOWABLE_WASTAGE"
        PRODUCTION_GATE = "PRODUCTION_GATE"
        BRAND = "BRAND"
        CUSTOMER_NAME = "CUSTOMER_NAME"
        PROJECT = "PROJECT"
        LOCATION = "LOCATION"
        ESTIMATED_QUANTITY = "ESTIMATED_QUANTITY"
        SHEETS_USED = "SHEETS_USED"
        WASTAGE_NESTED = "WASTAGE_NESTED"
        STATUS = "STATUS"
        PLANNED_CUT_DATE = "PLANNED_CUT_DATE"
    
    class PRODUCTION_PLANNING:
        """03 Production Planning columns."""
        SCHEDULE_ID = "SCHEDULE_ID"
        TAG_SHEET_ID = "TAG_SHEET_ID"
        PLANNED_DATE = "PLANNED_DATE"
        SHIFT = "SHIFT"
        MACHINE_ASSIGNED = "MACHINE_ASSIGNED"
        PLANNED_QUANTITY = "PLANNED_QUANTITY"
        STATUS = "STATUS"
        CREATED_BY = "CREATED_BY"
        CREATED_AT = "CREATED_AT"
        UPDATED_BY = "UPDATED_BY"
        UPDATED_AT = "UPDATED_AT"
        CLIENT_REQUEST_ID = "CLIENT_REQUEST_ID"
        TRACE_ID = "TRACE_ID"
        REMARKS = "REMARKS"
    
    class PRODUCTION_PLANNING_STAGING:
        """03h Production Planning Staging columns."""
        SCHEDULE_ID = "SCHEDULE_ID"
        TAG_SHEET_ID = "TAG_SHEET_ID"
        PLANNED_DATE = "PLANNED_DATE"
        SHIFT = "SHIFT"
        MACHINE_ASSIGNED = "MACHINE_ASSIGNED"
        PLANNED_QUANTITY = "PLANNED_QUANTITY"
        STATUS = "STATUS"
        REQUESTED_BY = "REQUESTED_BY"
        API_STATUS = "API_STATUS"
        API_MESSAGE = "API_MESSAGE"

    class NESTING_LOG:
        """04 Nesting Execution Log columns."""
        NEST_SESSION_ID = "NEST_SESSION_ID"
        TAG_SHEET_ID = "TAG_SHEET_ID"
        TIMESTAMP = "TIMESTAMP"
        BRAND = "BRAND"
        SHEETS_CONSUMED_VIRTUAL = "SHEETS_CONSUMED_VIRTUAL"
        EXPECTED_CONSUMPTION_M2 = "EXPECTED_CONSUMPTION_M2"
        WASTAGE_PERCENTAGE = "WASTAGE_PERCENTAGE"
        PLANNED_DATE = "PLANNED_DATE"
        REMNANT_ID_GENERATED = "REMNANT_ID_GENERATED"
        FILLER_IDS_GENERATED = "FILLER_IDS_GENERATED"
        FILE_HASH = "FILE_HASH"
        CLIENT_REQUEST_ID = "CLIENT_REQUEST_ID"

    
    class EXCEPTION_LOG:
        """99 Exception Log columns."""
        EXCEPTION_ID = "EXCEPTION_ID"
        CREATED_AT = "CREATED_AT"
        SOURCE = "SOURCE"
        RELATED_TAG_ID = "RELATED_TAG_ID"
        RELATED_TXN_ID = "RELATED_TXN_ID"
        MATERIAL_CODE = "MATERIAL_CODE"
        QUANTITY = "QUANTITY"
        REASON_CODE = "REASON_CODE"
        SEVERITY = "SEVERITY"
        STATUS = "STATUS"
        SLA_DUE = "SLA_DUE"
        RESOLUTION_ACTION = "RESOLUTION_ACTION"
    
    class USER_ACTION_LOG:
        """98 User Action Log columns."""
        ACTION_ID = "ACTION_ID"
        TIMESTAMP = "TIMESTAMP"
        USER_ID = "USER_ID"
        ACTION_TYPE = "ACTION_TYPE"
        TARGET_TABLE = "TARGET_TABLE"
        TARGET_ID = "TARGET_ID"
        OLD_VALUE = "OLD_VALUE"
        NEW_VALUE = "NEW_VALUE"
        NOTES = "NOTES"
    
    class MATERIAL_MASTER:
        """05a Material Master columns."""
        MAPPING_ID = "MAPPING_ID"
        NESTING_DESCRIPTION = "NESTING_DESCRIPTION"
        CANONICAL_CODE = "CANONICAL_CODE"
        DEFAULT_SAP_CODE = "DEFAULT_SAP_CODE"
        UOM = "UOM"
        SAP_UOM = "SAP_UOM"
        CONVERSION_FACTOR = "CONVERSION_FACTOR"
        NOT_TRACKED = "NOT_TRACKED"
        ACTIVE = "ACTIVE"
        NOTES = "NOTES"
        UPDATED_AT = "UPDATED_AT"
        UPDATED_BY = "UPDATED_BY"
    
    class MAPPING_OVERRIDE:
        """05b Mapping Override columns."""
        OVERRIDE_ID = "OVERRIDE_ID"
        SCOPE_TYPE = "SCOPE_TYPE"
        SCOPE_VALUE = "SCOPE_VALUE"
        NESTING_DESCRIPTION = "NESTING_DESCRIPTION"
        CANONICAL_CODE = "CANONICAL_CODE"
        SAP_CODE = "SAP_CODE"
        ACTIVE = "ACTIVE"
        EFFECTIVE_FROM = "EFFECTIVE_FROM"
        EFFECTIVE_TO = "EFFECTIVE_TO"
        CREATED_BY = "CREATED_BY"
        CREATED_AT = "CREATED_AT"
    
    class LPO_MATERIAL_BRAND_MAP:
        """05c LPO Material Brand Map columns."""
        MAP_ID = "MAP_ID"
        LPO_ID = "LPO_ID"
        CANONICAL_CODE = "CANONICAL_CODE"
        SAP_CODE = "SAP_CODE"
        PRIORITY = "PRIORITY"
        ACTIVE = "ACTIVE"
        NOTES = "NOTES"
    
    class MAPPING_HISTORY:
        """05d Mapping History columns."""
        HISTORY_ID = "HISTORY_ID"
        INGEST_LINE_ID = "INGEST_LINE_ID"
        NESTING_DESCRIPTION = "NESTING_DESCRIPTION"
        CANONICAL_CODE = "CANONICAL_CODE"
        SAP_CODE = "SAP_CODE"
        DECISION = "DECISION"
        USER_ID = "USER_ID"
        TRACE_ID = "TRACE_ID"
        CREATED_AT = "CREATED_AT"
        NOTES = "NOTES"
    
    class MAPPING_EXCEPTION:
        """05e Mapping Exception columns."""
        EXCEPTION_ID = "EXCEPTION_ID"
        INGEST_LINE_ID = "INGEST_LINE_ID"
        NESTING_DESCRIPTION = "NESTING_DESCRIPTION"
        STATUS = "STATUS"
        ASSIGNED_TO = "ASSIGNED_TO"
        CREATED_AT = "CREATED_AT"
        TRACE_ID = "TRACE_ID"
        RESOLUTION_NOTES = "RESOLUTION_NOTES"
    
    class PARSED_BOM:
        """06a Parsed BOM columns."""
        BOM_LINE_ID = "BOM_LINE_ID"
        NEST_SESSION_ID = "NEST_SESSION_ID"
        LINE_NUMBER = "LINE_NUMBER"
        MATERIAL_TYPE = "MATERIAL_TYPE"
        NESTING_DESCRIPTION = "NESTING_DESCRIPTION"
        CANONICAL_CODE = "CANONICAL_CODE"
        SAP_CODE = "SAP_CODE"
        QUANTITY = "QUANTITY"
        UOM = "UOM"
        CANONICAL_QUANTITY = "CANONICAL_QUANTITY"
        CANONICAL_UOM = "CANONICAL_UOM"
        MAPPING_DECISION = "MAPPING_DECISION"
        HISTORY_ID = "HISTORY_ID"
        CREATED_AT = "CREATED_AT"
        TRACE_ID = "TRACE_ID"


# Mapping from Sheet logical name to Column class
SHEET_COLUMNS = {
    Sheet.CONFIG: Column.CONFIG,
    Sheet.LPO_MASTER: Column.LPO_MASTER,
    Sheet.TAG_REGISTRY: Column.TAG_REGISTRY,
    Sheet.PRODUCTION_PLANNING: Column.PRODUCTION_PLANNING,
    Sheet.NESTING_LOG: Column.NESTING_LOG,
    Sheet.EXCEPTION_LOG: Column.EXCEPTION_LOG,
    Sheet.USER_ACTION_LOG: Column.USER_ACTION_LOG,
    Sheet.MATERIAL_MASTER: Column.MATERIAL_MASTER,
    Sheet.MAPPING_OVERRIDE: Column.MAPPING_OVERRIDE,
    Sheet.LPO_MATERIAL_BRAND_MAP: Column.LPO_MATERIAL_BRAND_MAP,
    Sheet.MAPPING_HISTORY: Column.MAPPING_HISTORY,
    Sheet.MAPPING_EXCEPTION: Column.MAPPING_EXCEPTION,
    Sheet.PARSED_BOM: Column.PARSED_BOM,
}

